config:
  title: PyHDX app

main_controller:
  type: peptide

sources:
  main:
    type: table

transforms:
  d_uptake_src:
    type: table_source
    source: main
    table: d_uptake
  k_int_src:
    type: table_source
    source: main
    table: k_int
  k_int_replace:
    type: generic
    source: k_int_src
    pd_function: replace
    kwargs:
      to_replace: 0
      value: .NAN

opts:
  base:
    type: generic
    responsive: True
    framewise: True
    show_grid: True
  d_uptake:
    type: generic
    logx: True
    xlabel: Time (s)
    ylabel: D uptake
    tools:
      - hover
  k_int:
    type: generic
    logy: True
    xlabel: Amino acid
    ylabel: Intrinsic rate (s⁻¹)
    tools:
      - count


tools:
  hover:
    type: hover
    tooltips:
      - ["Time (s)", '$x']
      - ['D-uptake', '$y']
  count:
    type: hover
    tooltips:
      - [ "Amino acid", '@aa' ]
      - [ "Intrinsic rate", '@k_int' ]

views:
  peptide_uptake:
    type: curve
    source: d_uptake_src
    opts:
      - base
      - d_uptake

    x: time
    y: sum

  aa_uptake:
    type: curve
    source: d_uptake_src
    opts:
      - base
      - d_uptake
    x: time
    y: aa_0
    y_objects: !regexp aa_\d

  k_int:
    type: bars
    source: k_int_replace
    opts:
      - base
      - k_int
    x: index
    y: k_int
#    vdims:
#      - aa

controllers:
  peptide:
