config:
  title: PyHDX app

main_controller:
  type: pyhdx
  #kwargs: ...

sources:
  main:
    type: pyhdx
  pdb:
    type: pdb
  metadata:
    type: dict

transforms:
  peptide_src:
    type: table_source
    source: main
    table: peptides
  rfu_src:
    type: table_source
    source: main
    table: rfu
  drfu_src:
    type: table_source
    source: main
    table: drfu

opts:
  base:
    type: generic
    responsive: True
    framewise: True
    show_grid: True
    shared_axes: False  # doesnt seem to do anything
  errorbars:
    type: generic
    line_alpha: 0.5
    line_color: '#8c8c8c'
    apply_ranges: False
    hooks:
      - handle: glyph
        attr: upper_head.line_color
        value: '#8c8c8c'
      - handle: glyph
        attr: lower_head.line_color
        value: '#8c8c8c'
  scatter:
    type: generic
    size: 8
  rfu_cmap:
    type: cmap
    field: rfu
  drfu_cmap:
    type: cmap
    field: drfu
  info_log:
    type: generic
    title: Log Window
  debug_log:
    type: generic
    title: Debug Log

tools:
  coverage_hover:
    type: hover
    tooltips:
      - ['peptide_id', '$index']
      - ['start, end', '@start, @end']
      - ['RFU', '@rfu']
      - ['D (corrected)', '@uptake_corrected']
      - ['sequence', '@sequence']
  rfu_hover:
    type: hover
    tooltips:
      - ['Residue', '@r_number']
      - ['RFU', '@rfu']
    # mode: vline
    #only show closest hit:
    #https://stackoverflow.com/questions/36434562/displaying-only-one-tooltip-when-using-the-hovertool-tool
    #https://github.com/bokeh/bokeh/issues/9087
  drfu_hover:
    type: hover
    tooltips:
      - [ 'Residue', '@r_number' ]
      - [ 'ΔRFU', '@drfu' ]



views:
  logging_info:
    type: logging
    logger: pyhdx
    level: 20
    opts:
      - info_log
  logging_debug:
    type: logging
    logger: pyhdx
    level: 10
    opts:
      - debug_log

modules:
  coverage_view:
    transforms:
      coverage_select:
        type: cross_section
        source: peptide_src
        n_levels: 2
      coverage_rectangles:
        type: rectangle_layout
        source: coverage_select
        left: start
        right: end
        passthrough:
          - rfu
          - uptake_corrected
          - sequence
          - start
          - end
    opts:
      coverage:
        type: generic
        color: rfu
        colorbar: True
        xlabel: Residue Number
        ylabel : ''
        yticks: 0
        title: Peptide coverage
        tools:
          - coverage_hover
    views:
      coverage:
        type: rectangles
        source: coverage_rectangles
        opts:
          - base
          - coverage
          - rfu_cmap
        vdims:
          - rfu
          - uptake_corrected
          - sequence
          - start
          - end

  rfu:
    transforms:
      rfu_select:
        type: cross_section
        source: rfu_src
        n_levels: -1  # todo change to -1?
    opts:
      rfu_scatter:
        type: generic
        xlabel: Residue Number
        ylabel: RFU
        title: RFU Scatter
        color: rfu
        colorbar: True
        ylim: [0, null]
        tools:
          - rfu_hover
    views:
      rfu_scatter:
        type: scatter
        source: rfu_select
        x: r_number
        y: rfu
        opts:
          - base
          - scatter
          - rfu_scatter
          - rfu_cmap
      rfu_errorbars:
        type: errorbars
        source: rfu_select
        opts:
          - base
          - errorbars
        x: r_number
        y: rfu
        err: rfu_sd
      rfu_overlay:
        type: overlay
        views:
          - rfu_scatter
          - rfu_errorbars

  drfu_view:
    transforms:
      drfu_comparison_select:
        type: cross_section
        source: drfu_src
        n_levels: -1
    opts:
      drfu_axes:
        type: generic
        xlabel: Residue Number
        ylabel: ΔRFU
        title: ΔRFU Scatterplot
        color: drfu
        colorbar: True
        tools:
          - drfu_hover
    views:
      drfu_scatter:
        type: scatter
        source: drfu_comparison_select
        x: r_number
        y: drfu
        opts:
          - base
          - scatter
          - drfu_axes
          - drfu_cmap
      drfu_errorbars:
        type: errorbars
        source: drfu_comparison_select
        opts:
          - base
          - errorbars
        x: r_number
        y: drfu
        err: drfu_sd
      drfu_overlay:
        type: overlay
        views:
          - drfu_scatter
          - drfu_errorbars

  protein_view:
    transforms:
      protein_src:
        type: select
        sources:
          rfu: rfu_select
          drfu: drfu_comparison_select
         #  d_uptake: d_uptake_select


    views:
      protein:
        type: pdbemolstar_colors
        sources:
          pdb: pdb
          color: protein_src
        hide_water: True
        hide_non_standard: True
        hide_heteroatoms: True
        hide_carbs: True
        hide_expand_icon: True
        opts:
          - rfu_cmap
          - drfu_cmap

        dependencies:
          opts:
            - rfu_cmap
            - drfu_cmap


  peptides:
    transforms:
      peptide_pipe:
        type: pipe
        source: peptide_src
        pipe:
          - function: xs
            args:
              - rfu
            kwargs:
              axis: 1
              level: -1
              drop_level: False
          - function: stack
            kwargs:
              level: 1
          - function: unstack
            kwargs:
              level: 0
          - function: swaplevel
            kwargs:
              axis: 1
          - function: dropna
            kwargs:
              axis: 0
              how: all
          - function: dropna
            kwargs:
              axis: 1
              how: all
      peptide_select:
        type: cross_section
        source: peptide_pipe
        n_levels: -1
    opts:
      peptide_scatter:
        type: generic
        logx: True
        ylim: [ 0, null ]
        xlabel: Exposure time (s)
        ylabel: RFU
    views:
      peptide_scatter:
        type: scatter
        source: peptide_select
        x: exposure
        y: rfu
        opts:
          - base
          - scatter
          - peptide_scatter

controllers:
  - global_settings
  - peptide_rfu_file_input
  - diff
  - color_transform
  - protein  #rename: NGL?
  - graph
  - file_export
  - figure_export
  - session_manager
