# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.4.3.dev39+gb3f4b9c.d20230805'
__version_tuple__ = version_tuple = (0, 4, 3, 'dev39', 'gb3f4b9c.d20230805')
