cluster:
  scheduler_address: "127.0.0.1:52123"
  n_workers: 10

server:
  assets_dir: ~/.pyhdx/assets
  log_dir: ~/.pyhdx/logs
  database_dir : ~/.hdxms_datasets/datasets

fitting:
  dtype: float64
  device: cpu

analysis:
  drop_first: 2
  weight_exponent: 1.0

plotting:
  # Sizes are in mm
  ncols: 2
  page_width: 160
  cbar_width: 2.5
  peptide_coverage_aspect: 3
  peptide_mse_aspect: 3
  residue_scatter_aspect: 3
  dG_aspect: 2.5
  linear_bars_aspect: 30
  loss_aspect: 2.5
  rainbowclouds_aspect: 4
